version: "2"

volumes:
  cache:
  redis:
  postgres:
  pg_data:
    driver: local

services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: redhill_be
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redhill_be_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:3.2.10
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  base:
    build: .
    volumes:
      - .:/app:z
      - cache:/cache
    environment:
      SPROCKETS_CACHE: /cache
      DATABASE_URL: postgres://spotilla_be:password@db/redhill_be?
      QUEUE: "*"
    command: echo Starting services...

  be:
    extends:
      service: base
    ports:
      - 3000:3000
    links:
      - db
      - redis
    command: rails server -b [::]

networks:
  default:
    external:
      name: redhill
